spring.application.name=notification-service
server.port = 8086

#db
spring.datasource.url = jdbc:postgresql://localhost:5432/learning-notification-db
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=${spring.application.name}